// Service Worker generated by PWA Forge
const CACHE_NAME = 'v1-scripture-hub';
const ASSETS = [".","index.html","css/app.css","js/app.js","images/icon-192x192.png","images/icon-512x512.png","data/bible-books.json","data/bible-verses.json"];

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => {
      return cache.addAll(ASSETS);
    })
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keyList) => {
      return Promise.all(keyList.map((key) => {
        if (key !== CACHE_NAME) {
          return caches.delete(key);
        }
      }));
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
